<?php

namespace ILANEO\CongeBundle\Repository;

/**
 * askVacationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class askVacationRepository extends \Doctrine\ORM\EntityRepository
{
}
