# notre bundle principale
ilaneo_conge:
    resource: "@ILANEOCongeBundle/Resources/config/routing.yml"
    prefix:   /


#app:
    #resource: '@AppBundle/Controller/'
    #type: annotation

# le bundle qui gére la gestion des utilisateurs
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#le bundle qui gére les routes pour l'intégration du calendrier
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

#le bundle qui gére les calendrier
adesigns_calendar:
  resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"
