ilaneo_conge_connexion:
    path:     /
    defaults: { _controller: ILANEOCongeBundle:Employe:index }

#ilaneo_conge_verifLogin:
    #path:     /verifLogin
    #defaults: { _controller: ILANEOCongeBundle:Employe:verifLogin }

ilaneo_conge_demandeConge:
    path:     /user/ask
    defaults: { _controller: ILANEOCongeBundle:Employe:ask }

ilaneo_conge_visualisationConge:
    path:     /user/visualization
    defaults: { _controller: ILANEOCongeBundle:Employe:visualization }

ilaneo_conge_attributionConge:
    path:     /admin/test
    defaults: { _controller: ILANEOCongeBundle:Admin:test }

ilaneo_conge_modificationListeEmp:
    path:     /admin/edit_emp
    defaults: { _controller: ILANEOCongeBundle:Admin:edit }

#ilaneo_conge_ajoutEmp:
    #path:     /ajoutEmp
    #defaults: { _controller: ILANEOCongeBundle:Admin:ajout }

ilaneo_conge_annualVacation:
    path:   /annualVacation
    defaults: { _controller: ILANEOCongeBundle:Employe:AnnualVacation}

ilaneo_conge_SickVacation:
    path:   /SickVacation
    defaults: { _controller: ILANEOCongeBundle:Employe:SickVacation}

ilaneo_conge_UnpaidVacation:
    path:   /UnpaidVacation
    defaults: { _controller: ILANEOCongeBundle:Employe:UnpaidVacation}

ilaneo_conge_ExceptionalVacation:
    path:   /ExceptionalVacation
    defaults: { _controller: ILANEOCongeBundle:Employe:ExceptionalVacation}
    
ilaneo_conge_AuthorizationVacation:
    path:   /AuthorizationVacation
    defaults: { _controller: ILANEOCongeBundle:Employe:AuthorizationVacation}

#fos_user_security_login:
    #path:    /log
    #defaults: { _controller: ILANEOCongeBundle:Security:login}

    

