ilaneo_conge_connexion:
    path:     /
    defaults: { _controller: ILANEOCongeBundle:employe:index }

#ilaneo_conge_accueil:
    #path:     /main/{id}
    #defaults: { _controller: ILANEOCongeBundle:employe:connexion }
    #requirements:
        #id: \d+

ilaneo_conge_demandeConge:
    path:     /user/ask
    defaults: { _controller: ILANEOCongeBundle:employe:ask }

ilaneo_conge_visualisationConge:
    path:     /user/visualization
    defaults: { _controller: ILANEOCongeBundle:employe:visualization }

ilaneo_conge_attributionConge:
    path:     /admin/test
    defaults: { _controller: ILANEOCongeBundle:Admin:test }

ilaneo_conge_modificationListeEmp:
    path:     /admin/edit_emp
    defaults: { _controller: ILANEOCongeBundle:Admin:edit }

#ilaneo_conge_ajoutEmp:
    #path:     /ajoutEmp
    #defaults: { _controller: ILANEOCongeBundle:Admin:ajout }



