# page d'accueil
ilaneo_conge_connexion:
    path:     /
    defaults: { _controller: ILANEOCongeBundle:Employe:index }

#ilaneo_conge_verifLogin:
    #path:     /verifLogin
    #defaults: { _controller: ILANEOCongeBundle:Employe:verifLogin }

# page demander congé
ilaneo_conge_demandeConge:
    path:    /admin/ask
    defaults: { _controller: ILANEOCongeBundle:Employe:ask }


#page liste des demandes
ilaneo_conge_attributionConge:
    path:     /admin/test
    defaults: { _controller: ILANEOCongeBundle:Admin:test }

#page liste des employés
ilaneo_conge_modificationListeEmp:
    path:     /admin/edit_emp
    defaults: { _controller: ILANEOCongeBundle:Admin:edit }

#page ajouter employé
ilaneo_conge_ajoutEmp:
    path:     /admin/ajoutEmp
    defaults: { _controller: ILANEOCongeBundle:Admin:ajout }


ilaneo_conge_annualVacation:
    path:   /annualVacation
    defaults: { _controller: ILANEOCongeBundle:Employe:AnnualVacation}

ilaneo_conge_SickVacation:
    path:   /SickVacation
    defaults: { _controller: ILANEOCongeBundle:Employe:SickVacation}

ilaneo_conge_UnpaidVacation:
    path:   /UnpaidVacation
    defaults: { _controller: ILANEOCongeBundle:Employe:UnpaidVacation}

ilaneo_conge_ExceptionalVacation:
    path:   /ExceptionalVacation
    defaults: { _controller: ILANEOCongeBundle:Employe:ExceptionalVacation}
    
ilaneo_conge_AuthorizationVacation:
    path:   /AuthorizationVacation
    defaults: { _controller: ILANEOCongeBundle:Employe:AuthorizationVacation}


#page modifier profile
ilaneo_conge_profileEdit:
    path: /user/profileEdit
    defaults: {_controller: ILANEOCongeBundle:Employe:profileEdit}

#page mot de passe oublié
ilaneo_conge_resetPassword:
    path: /resetPassword
    defaults: {_controller: ILANEOCongeBundle:Employe:resetPassword}

# mes demandes
ilaneo_conge_myRequests:
    path: /user/myRequests
    defaults: {_controller: ILANEOCongeBundle:Employe:myRequests}

ilaneo_conge_calculateDate:
    path: /user/claculateDate
    defaults: {_controller: ILANEOCongeBundle:Employe:calculateDate}
    options:
        expose: true

